// <auto-generated />
using System;
using EvalSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvalSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EvalSystemDbContext))]
    [Migration("20260319162422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvalSystem.Domain.Entities.Evaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("TecnologiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TiempoLimiteMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TecnologiaId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.EvaluacionSeccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.ToTable("EvaluacionSecciones");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.OpcionRespuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaId");

                    b.ToTable("OpcionesRespuesta");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.Pregunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explicacion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.Property<Guid>("SeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TiempoSegundos")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SeccionId");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.ProcesoCandidato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProcesoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ProcesoId", "CandidatoId")
                        .IsUnique();

                    b.ToTable("ProcesoCandidatos");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.ProcesoEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProcesoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("ProcesoId", "EvaluacionId")
                        .IsUnique();

                    b.ToTable("ProcesoEvaluaciones");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.ProcesoSeleccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Puesto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreadorId");

                    b.ToTable("ProcesosSeleccion");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expira")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Revocado")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.RespuestaCandidato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("EsCorrecta")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("OpcionSeleccionadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PuntajeObtenido")
                        .HasColumnType("int");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TiempoRespuestaSegundos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OpcionSeleccionadaId");

                    b.HasIndex("PreguntaId");

                    b.HasIndex("SesionId", "PreguntaId")
                        .IsUnique();

                    b.ToTable("RespuestasCandidato");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.ResultadoEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrechasIdentificadas")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAnalisis")
                        .HasColumnType("datetime2");

                    b.Property<string>("FortalezasIdentificadas")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RecomendacionIA")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ScorePorSeccion")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("ScoreTotal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("SesionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SesionId")
                        .IsUnique();

                    b.ToTable("ResultadosEvaluacion");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.SesionEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ProcesoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ScoreMaximo")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreObtenido")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("ProcesoId");

                    b.ToTable("SesionesEvaluacion");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.Tecnologia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Tecnologias");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.Evaluacion", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.Tecnologia", "Tecnologia")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("TecnologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnologia");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.EvaluacionSeccion", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.Evaluacion", "Evaluacion")
                        .WithMany("Secciones")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.OpcionRespuesta", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.Pregunta", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.Pregunta", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.EvaluacionSeccion", "Seccion")
                        .WithMany("Preguntas")
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.ProcesoCandidato", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.Usuario", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvalSystem.Domain.Entities.ProcesoSeleccion", "Proceso")
                        .WithMany("Candidatos")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.ProcesoEvaluacion", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.Evaluacion", "Evaluacion")
                        .WithMany("ProcesoEvaluaciones")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvalSystem.Domain.Entities.ProcesoSeleccion", "Proceso")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.ProcesoSeleccion", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.RespuestaCandidato", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.OpcionRespuesta", "OpcionSeleccionada")
                        .WithMany()
                        .HasForeignKey("OpcionSeleccionadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EvalSystem.Domain.Entities.Pregunta", "Pregunta")
                        .WithMany("Respuestas")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvalSystem.Domain.Entities.SesionEvaluacion", "Sesion")
                        .WithMany("Respuestas")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcionSeleccionada");

                    b.Navigation("Pregunta");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.ResultadoEvaluacion", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.SesionEvaluacion", "Sesion")
                        .WithOne("Resultado")
                        .HasForeignKey("EvalSystem.Domain.Entities.ResultadoEvaluacion", "SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.SesionEvaluacion", b =>
                {
                    b.HasOne("EvalSystem.Domain.Entities.Usuario", "Candidato")
                        .WithMany("Sesiones")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvalSystem.Domain.Entities.Evaluacion", "Evaluacion")
                        .WithMany("Sesiones")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EvalSystem.Domain.Entities.ProcesoSeleccion", "Proceso")
                        .WithMany()
                        .HasForeignKey("ProcesoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Candidato");

                    b.Navigation("Evaluacion");

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.Evaluacion", b =>
                {
                    b.Navigation("ProcesoEvaluaciones");

                    b.Navigation("Secciones");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.EvaluacionSeccion", b =>
                {
                    b.Navigation("Preguntas");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.Pregunta", b =>
                {
                    b.Navigation("Opciones");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.ProcesoSeleccion", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.SesionEvaluacion", b =>
                {
                    b.Navigation("Respuestas");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.Tecnologia", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("EvalSystem.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
